import { browserRequest } from './http-request.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp,readFile,rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { once } from 'node:events';
import { ConnectedService } from '../lib/connected/service.mjs';
import { Vault } from '../lib/connected/vault.mjs';
import { capabilities,SCOPES } from '../lib/connected/oauth.mjs';
import { freeSlots, zonedInstant, email,safeLink,iso,mimeSubject } from '../lib/connected/common.mjs';
import { normalizeEvent,normalizeMessage } from '../lib/connected/providers.mjs';
import { createApp } from '../server.mjs';
import { makeFixture,fixtureEnv,seed } from './connected-fixture.mjs';
const setup=async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'essentiel-test-')),f=makeFixture(),s=new ConnectedService({filename:path.join(dir,'vault'),env:fixtureEnv,fetchImpl:f.fetch});return {s,f,dir,cleanup:()=>rm(dir,{recursive:true,force:true})};};
async function scoped(fn){const t=await setup();try{await fn(t);}finally{await t.cleanup();}}
const proposal=(s,p='google',kind='task',payload={title:'TEST task',notes:'Test',listId:'list-google',due:'2026-10-10'})=>s.preview({provider:p,kind,payload});
const approve=(s,a)=>s.execute({id:a.id,approvalHash:a.approvalHash,approved:true});
function future(){const d=new Date();d.setDate(d.getDate()+2);d.setUTCHours(14,0,0,0);return {start:d.toISOString(),end:new Date(+d+1800000).toISOString()};}

test('connected: unconfigured connectors stay disconnected; no fake accounts',()=>scoped(async({s})=>{const d=s.status();assert.equal(d.providers.length,2);assert.ok(d.providers.every(p=>!p.connected));assert.deepEqual(d.actions,[]);}));
test('connected: least-privilege OAuth request has PKCE, state, browser binding, no write scope',()=>scoped(async({s})=>{const auth=s.oauth.start('google',['mail'],'http://127.0.0.1:8787'),u=new URL(auth.url);assert.equal(u.searchParams.get('code_challenge_method'),'S256');assert.ok(u.searchParams.get('state').length>30);assert.ok(auth.cookie.includes('HttpOnly'));assert.ok(auth.cookie.includes('SameSite=Lax'));assert.ok(!auth.requested.includes(SCOPES.google.drafts));assert.ok(!auth.requested.includes(SCOPES.google.calendar));}));
test('connected: OAuth rejects forged state and browser cookie',()=>scoped(async({s})=>{const auth=s.oauth.start('google',['mail'],'http://127.0.0.1:8787'),params=new URL(auth.url).searchParams;params.set('code','TEST');await assert.rejects(s.oauth.callback('google',params,''),e=>e.code==='OAUTH_STATE_INVALID');params.set('state','forged');await assert.rejects(s.oauth.callback('google',params,auth.cookie),e=>e.code==='OAUTH_STATE_INVALID');}));
test('connected: OAuth code exchange stores server tokens, prevents replay and honors actual grants',()=>scoped(async({s,f})=>{f.grants.google=SCOPES.google.mail;const a=s.oauth.start('google',['mail','drafts'],'http://127.0.0.1:8787'),params=new URL(a.url).searchParams;params.set('code','TEST');await s.oauth.callback('google',params,a.cookie);assert.equal(s.status().providers[0].capabilities.drafts,false);assert.equal(s.status().providers[0].capabilities.mail,true);const serialized=JSON.stringify(s.status());assert.ok(!serialized.includes('TEST-TOKEN'));assert.ok(!serialized.includes('refreshToken'));await assert.rejects(s.oauth.callback('google',params,a.cookie),e=>e.code==='OAUTH_STATE_INVALID');}));
test('connected: OAuth cannot silently replace a different account',()=>scoped(async({s,f})=>{seed(s,['google']);f.profileSuffix='-OTHER';const a=s.oauth.start('google',['mail'],'http://127.0.0.1:8787'),params=new URL(a.url).searchParams;params.set('code','TEST');await assert.rejects(s.oauth.callback('google',params,a.cookie),e=>e.code==='ACCOUNT_CHANGED');assert.equal(s.vault.state().accounts.google.subject,'TEST-google');}));
test('connected: OAuth denial consumes state without connecting',()=>scoped(async({s})=>{const a=s.oauth.start('microsoft',['mail'],'http://127.0.0.1:8787'),params=new URL(a.url).searchParams;params.set('error','access_denied');await assert.rejects(s.oauth.callback('microsoft',params,a.cookie),e=>e.code==='OAUTH_DENIED');assert.equal(s.status().providers[1].connected,false);}));
test('connected: concurrent expiry checks refresh a token only once',()=>scoped(async({s,f})=>{seed(s,['google']);s.vault.state().accounts.google.expiresAt=0;await Promise.all([s.oauth.token('google'),s.oauth.token('google')]);assert.equal(f.calls.filter(c=>c.url.includes('/token')).length,1);}));
test('connected: synchronize both mailboxes, calendars and task lists through provider adapters',()=>scoped(async({s})=>{seed(s);for(const p of ['google','microsoft']){const x=await s.sync(p);assert.equal(x.errors.length,0);assert.equal(x.messages.length,1);assert.equal(x.calendars.length,1);assert.equal(x.tasks.length,1);assert.equal(x.messages[0].provider,p);}}));
test('connected: errors retain previous sources and are not reported as empty inboxes',()=>scoped(async({s,f})=>{seed(s,['google']);await s.sync('google');f.failures.push({path:'/messages',status:503});const x=await s.sync('google');assert.equal(x.messages.length,1);assert.equal(x.errors[0].service,'mail');}));
test('connected: document search reaches Google Drive and OneDrive endpoints',()=>scoped(async({s,f})=>{seed(s);for(const p of ['google','microsoft']){const result=await s.providers.files(p,"document O'Brien");assert.equal(result.items.length,1);assert.ok(result.items[0].url.startsWith('https://'));}assert.ok(f.calls.some(x=>x.url.includes('name+contains')));assert.ok(f.calls.some(x=>x.url.includes('search(q=')));}));
test('connected: remote links and pagination cannot leave the provider allowlist',()=>scoped(async({s,f})=>{seed(s);const count=f.calls.length;await assert.rejects(s.providers.page('google','files','https://evil.test/steal'),e=>e.code==='UNTRUSTED_NEXT_LINK');assert.equal(f.calls.length,count);assert.equal(safeLink('javascript:alert(1)','google'),'');assert.equal(safeLink('https://google.com.evil.test/','google'),'');}));
test('connected: preview does not write; execution requires exact hash and explicit approval',()=>scoped(async({s,f})=>{seed(s,['google']);await s.sync('google');const a=await proposal(s),before=f.calls.filter(c=>c.method==='POST').length;await assert.rejects(s.execute({id:a.id,approved:false,approvalHash:a.approvalHash}),e=>e.code==='APPROVAL_REQUIRED');await assert.rejects(s.execute({id:a.id,approved:true,approvalHash:'changed'}),e=>e.code==='APPROVAL_REQUIRED');assert.equal(f.calls.filter(c=>c.method==='POST').length,before);assert.equal(a.status,'pending');}));
test('connected: real adapter task creation is read back; repeated action IDs cannot write twice',()=>scoped(async({s,f})=>{seed(s,['google']);await s.sync('google');const a=await proposal(s),result=await approve(s,a);assert.equal(result.status,'verified');assert.ok(result.receipt.id);assert.ok(result.receipt.verifiedAt);assert.equal(f.tasks.google.get(result.receipt.id).due,'2026-10-10T00:00:00Z');const count=f.calls.filter(c=>c.method==='POST').length;await assert.rejects(approve(s,a),e=>e.code==='ACTION_NOT_PENDING');assert.equal(f.calls.filter(c=>c.method==='POST').length,count);}));
test('connected: Microsoft To Do creation uses the selected list and date-only semantics',()=>scoped(async({s,f})=>{seed(s,['microsoft']);await s.sync('microsoft');const a=await proposal(s,'microsoft','task',{listId:'list-microsoft',title:'TEST task',notes:'',due:'2026-10-10'}),r=await approve(s,a);assert.equal(r.status,'verified');assert.equal(f.tasks.microsoft.get(r.receipt.id).dueDateTime.dateTime,'2026-10-10T00:00:00');}));
test('connected: creating drafts never calls a send endpoint',()=>scoped(async({s,f})=>{seed(s);for(const p of ['google','microsoft']){const a=await proposal(s,p,'draft',{to:'recipient@example.test',subject:'Réponse de test',body:'TEST FIXTURE only. Not sent.'}),r=await approve(s,a);assert.equal(r.status,'verified');assert.equal(f.drafts[p].size,1);}assert.ok(f.calls.every(c=>!c.url.match(/\/send(?:Mail)?(?:\?|$)/)));}));
test('connected: mail header injection and multiple recipients are rejected before writes',()=>scoped(async({s})=>{seed(s,['google']);await assert.rejects(proposal(s,'google','draft',{to:'a@example.test',subject:'Hello\r\nBcc: other@example.test',body:'Test'}),e=>e.code==='HEADER_INJECTION');assert.throws(()=>email('a@example.test, b@example.test'));}));
test('connected: forged sources cannot be used to authorize actions',()=>scoped(async({s})=>{seed(s,['google']);await assert.rejects(s.preview({provider:'google',kind:'draft',payload:{to:'a@example.test',subject:'Test',body:'Test'},source:{provider:'google',id:'not-cached'}}),e=>e.code==='SOURCE_NOT_FOUND');}));
test('connected: changed source blocks action before external write',()=>scoped(async({s,f})=>{seed(s,['microsoft']);await s.sync('microsoft');const a=await s.preview({provider:'microsoft',kind:'draft',payload:{to:'sender@example.test',subject:'Test',body:'Test'},source:{provider:'microsoft',id:'message-microsoft'}});f.sourceText='Changed source';const result=await approve(s,a);assert.equal(result.status,'blocked');assert.equal(f.drafts.microsoft.size,0);}));
test('connected: expired previews and missing write permissions are rejected',()=>scoped(async({s})=>{seed(s,['google']);await s.sync('google');const a=await proposal(s);a.expiresAt='2020-01-01T00:00:00Z';await assert.rejects(approve(s,a),e=>e.code==='PREVIEW_EXPIRED');s.vault.state().accounts.google.scopes=[SCOPES.google.tasks];await assert.rejects(proposal(s),e=>e.code==='PERMISSION_REQUIRED');}));
test('connected: bounded free-time calculation merges overlaps and preserves uncertainty outside scope',()=>{const events=[{start:'2026-10-10T10:00:00Z',end:'2026-10-10T11:00:00Z',busy:true},{start:'2026-10-10T10:30:00Z',end:'2026-10-10T12:00:00Z',busy:true}];const slots=freeSlots(events,'2026-10-10T09:00:00Z','2026-10-10T13:00:00Z',30,0);assert.deepEqual(slots.map(x=>x.start),['2026-10-10T09:00:00.000Z','2026-10-10T12:00:00.000Z']);});
test('connected: all-day Google events retain calendar timezone and DST boundaries',()=>{const e=normalizeEvent('google',{id:'test',start:{date:'2026-03-08'},end:{date:'2026-03-09'}},{id:'c',title:'Calendar',timeZone:'America/Toronto'});assert.equal(e.start,'2026-03-08T05:00:00.000Z');assert.equal(e.end,'2026-03-09T04:00:00.000Z');assert.equal(zonedInstant('2026-09-19T09:00:00','America/Toronto'),'2026-09-19T13:00:00.000Z');});
test('connected: fresh calendar conflict prevents a time-block creation',()=>scoped(async({s,f})=>{seed(s);await s.sync('google');await s.sync('microsoft');const times=future(),a=await proposal(s,'google','event',{calendarId:'calendar-google',title:'Test block',notes:'',...times});f.events.microsoft.push({id:'busy',subject:'Busy',start:{dateTime:times.start,timeZone:'UTC'},end:{dateTime:times.end,timeZone:'UTC'},showAs:'busy'});const r=await approve(s,a);assert.equal(r.status,'blocked');assert.equal(f.events.google.length,0);}));
test('connected: incomplete calendar pagination blocks availability instead of inventing free time',()=>scoped(async({s,f})=>{seed(s,['google']);await s.sync('google');f.partialEvents=true;const t=future();await assert.rejects(s.slots({from:t.start,to:t.end,minutes:15}),e=>e.code==='AVAILABILITY_UNKNOWN');}));
test('connected: time blocks use provider IDs and no participants, invitations or reminders',()=>scoped(async({s,f})=>{seed(s,['google']);await s.sync('google');const a=await proposal(s,'google','event',{calendarId:'calendar-google',title:'Test block',notes:'',...future()}),r=await approve(s,a);assert.equal(r.status,'verified');const call=f.calls.find(c=>c.method==='POST'&&c.url.includes('/events'));assert.equal(call.body.attendees,undefined);assert.equal(call.body.reminders.useDefault,false);assert.ok(call.url.endsWith('sendUpdates=none'));assert.ok(/^[0-9a-v]+$/.test(call.body.id));}));
test('connected: Microsoft calendar creates and verifies a personal event',()=>scoped(async({s,f})=>{seed(s,['microsoft']);await s.sync('microsoft');const a=await proposal(s,'microsoft','event',{calendarId:'calendar-microsoft',title:'Test block',notes:'',...future()}),r=await approve(s,a);assert.equal(r.status,'verified');const call=f.calls.find(c=>c.method==='POST'&&c.url.includes('/events'));assert.equal(call.body.transactionId,a.id);assert.equal(call.body.isReminderOn,false);assert.equal(call.body.attendees,undefined);}));
test('connected: completing tasks checks current version and verifies provider status',()=>scoped(async({s,f})=>{seed(s,['google']);await s.sync('google');const a=await proposal(s,'google','complete_task',{taskId:'task-google',listId:'list-google'});const r=await approve(s,a);assert.equal(r.status,'verified');assert.equal(f.tasks.google.get('task-google').status,'completed');}));
test('connected: concurrent task edits block completion before patching',()=>scoped(async({s,f})=>{seed(s,['google']);await s.sync('google');const a=await proposal(s,'google','complete_task',{taskId:'task-google',listId:'list-google'});f.tasks.google.get('task-google').etag='v3';assert.equal((await approve(s,a)).status,'blocked');assert.ok(!f.calls.some(c=>c.method==='PATCH'));}));
test('connected: ambiguous write failure stays uncertain and is never automatically retried',()=>scoped(async({s,f})=>{seed(s,['google']);await s.sync('google');const a=await proposal(s);f.failures.push({path:'/tasks/v1/lists/list-google/tasks',method:'POST',timeout:true});assert.equal((await approve(s,a)).status,'uncertain');await assert.rejects(approve(s,a),e=>e.code==='ACTION_NOT_PENDING');assert.equal(f.calls.filter(c=>c.method==='POST').length,1);}));
test('connected: failed read-back keeps returned object ID and can be verified without another write',()=>scoped(async({s,f})=>{seed(s,['microsoft']);const a=await proposal(s,'microsoft','draft',{to:'a@example.test',subject:'Test',body:'Test'});f.failures.push({path:'/messages/draft-',method:'GET',status:503});const r=await approve(s,a);assert.equal(r.status,'created_unverified');const id=r.receipt.id;assert.equal((await s.verify(a.id)).status,'verified');assert.equal(f.drafts.microsoft.size,1);assert.equal(r.receipt.id,id);}));
test('connected: encrypted persistence contains no readable tokens or source contents',()=>scoped(async({s,dir})=>{seed(s,['google']);await s.sync('google');await s.vault.unlock('correct horse battery staple');const raw=await readFile(path.join(dir,'vault'),'utf8');assert.ok(!raw.includes('TEST-TOKEN'));assert.ok(!raw.includes('google@example.test'));assert.ok(!raw.includes('Please review'));await s.vault.lock();assert.equal(s.status().vault.locked,true);assert.deepEqual(s.status().snapshots,{});await assert.rejects(s.vault.unlock('incorrect passphrase value'));await s.vault.unlock('correct horse battery staple');assert.equal(s.status().providers[0].connected,true);}));
test('connected: a process interrupted during execution reopens as uncertain, not pending',()=>scoped(async({s,dir})=>{seed(s,['google']);await s.sync('google');const a=await proposal(s);a.status='executing';await s.vault.unlock('correct horse battery staple');await s.vault.lock();const reopened=new Vault(path.join(dir,'vault'));await reopened.unlock('correct horse battery staple');assert.equal(reopened.state().actions[0].status,'uncertain');}));
test('connected: local disconnect removes credentials and cache without claiming provider revocation',()=>scoped(async({s})=>{seed(s,['google']);await s.sync('google');const result=await s.disconnect('google');assert.equal(result.revoked,false);assert.equal(s.status().providers[0].connected,false);assert.equal(s.status().snapshots.google,undefined);}));
test('connected: memory-only mode writes no file; erase removes encrypted persistence',()=>scoped(async({s,dir})=>{seed(s,['google']);await s.sync('google');assert.equal(existsSync(path.join(dir,'vault')),false);await s.vault.unlock('correct horse battery staple');await s.vault.erase();assert.equal(existsSync(path.join(dir,'vault')),false);assert.equal(s.status().providers[0].connected,false);}));
test('connected: vault changes are refused while a connector operation is active',()=>scoped(async({s})=>{s.active=1;await assert.rejects(s.manageVault('erase'),e=>e.code==='BUSY');await assert.rejects(s.disconnect('google'),e=>e.code==='BUSY');}));

async function withHTTP(fn){const dir=await mkdtemp(path.join(os.tmpdir(),'essentiel-http-')),f=makeFixture(),app=createApp({apiKey:'',connectorOptions:{filename:path.join(dir,'vault'),env:fixtureEnv,fetchImpl:f.fetch}});app.listen(0,'127.0.0.1');await once(app,'listening');const base=`http://127.0.0.1:${app.address().port}`;const post=(route,body,headers={})=>fetch(base+'/api/connected/'+route,{method:'POST',headers:{Origin:base,'Content-Type':'application/json','X-Essentiel-Request':'1',...headers},body:JSON.stringify(body)});try{await fn({base,post,f});}finally{app.closeAllConnections();await new Promise(r=>app.close(r));await rm(dir,{recursive:true,force:true});}}
test('connected HTTP: status and writes require the same-origin protection header',()=>withHTTP(async({base,post})=>{assert.equal((await fetch(base+'/api/connected/status')).status,403);assert.equal((await post('oauth/start',{provider:'google',features:['mail']},{Origin:'https://evil.test'})).status,403);assert.equal((await fetch(base+'/.data/connected.vault')).status,404);}));
test('connected HTTP: OAuth cross-site callback is validated and sanitized; full fixture sync runs through HTTP',()=>withHTTP(async({base,post,f})=>{const r=await post('oauth/start',{provider:'google',features:['mail','calendar','tasks']}),auth=await r.json(),state=new URL(auth.url).searchParams.get('state'),cookie=r.headers.get('set-cookie').split(';')[0];const callback=await browserRequest(base+'/oauth/google/callback?state='+state+'&code=TEST-SECRET-CODE',{headers:{Cookie:cookie,'Sec-Fetch-Site':'cross-site','Sec-Fetch-Mode':'navigate','Sec-Fetch-Dest':'document'},redirect:'manual'});assert.equal(callback.status,303);assert.ok(!callback.headers.get('location').includes('SECRET'));assert.equal((await post('sync',{provider:'google'})).status,200);const status=await (await fetch(base+'/api/connected/status',{headers:{'X-Essentiel-Request':'1'}})).json();assert.equal(status.snapshots.google.messages.length,1);assert.ok(!JSON.stringify(status).includes('TEST-TOKEN'));assert.ok(f.calls.length>5);}));
test('connected HTTP: production default never silently enters a synthetic mode',()=>withHTTP(async({base,post})=>{const result=await post('sync',{provider:'google'});assert.equal(result.status,409);const page=await (await fetch(base)).text();assert.ok(page.includes('/connected.js'));assert.equal((await fetch(base+'/workspace')).status,200);assert.equal((await post('send',{provider:'google'})).status,404);}));


test('connected: invalid normalized calendar days and times are rejected',()=>{
  for(const d of ['2026-02-30T12:00:00Z','2026-09-19T24:00:00Z','2026-09-19T12:00:00+01:60','2026-13-19T12:00:00Z'])assert.throws(()=>iso(d),{code:'INVALID_DATE'});
  assert.equal(iso('2024-02-29T12:00:00-04:00'),'2024-02-29T16:00:00.000Z');
});
test('connected: folded MIME subject preserves Unicode and encoded-word bounds',()=>{
  const subject='Réunion 🧑🏽‍💻 à Québec — 文書確認 '.repeat(5),encoded=mimeSubject(subject),words=encoded.split('\r\n ');
  assert.ok(words.every(w=>w.length<=75));assert.equal(words.map(w=>Buffer.from(w.slice(10,-2),'base64').toString('utf8')).join(''),subject);
});
test('connected: disappearance of any selected calendar blocks availability',()=>scoped(async({s})=>{
  seed(s);await s.sync('google');s.vault.state().selections.google={calendarIds:['calendar-google','removed-calendar']};
  await assert.rejects(s.freshAvailability(future().start,future().end),{code:'AVAILABILITY_UNKNOWN'});
}));
test('connected: disappearance of selected task list never silently substitutes another list',()=>scoped(async({s})=>{
  seed(s);await s.sync('google');s.vault.state().selections.google={listId:'removed-list'};const snapshot=await s.sync('google');
  assert.ok(snapshot.errors.some(x=>x.service==='tasks'&&x.code==='TARGET_UNAVAILABLE'));
}));
test('connected: source-linked Google draft re-reads unchanged source successfully',()=>scoped(async({s})=>{
  seed(s);await s.sync('google');const a=await s.preview({provider:'google',kind:'draft',payload:{to:'sender@example.test',subject:'Reviewed',body:'Test only'},source:{provider:'google',id:'message-google'}});
  assert.equal((await approve(s,a)).status,'verified');
}));
