import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { once } from 'node:events';
import { providerError, googleConsoleUrl } from '../lib/connected/provider-errors.mjs';
import { ConnectedService } from '../lib/connected/service.mjs';
import { createApp } from '../server.mjs';
import { SCOPES } from '../lib/connected/oauth.mjs';
import { makeFixture, fixtureEnv, seed } from './connected-fixture.mjs';
const URLS={mail:'https://gmail.googleapis.com/gmail/v1/users/me/messages',calendar:'https://www.googleapis.com/calendar/v3/users/me/calendarList',tasks:'https://tasks.googleapis.com/tasks/v1/users/@me/lists',files:'https://www.googleapis.com/drive/v3/files'};
const disabled=(service='gmail.googleapis.com')=>({error:{code:403,status:'PERMISSION_DENIED',message:'Sensitive upstream message must not be copied TEST-SECRET',details:[{'@type':'type.googleapis.com/google.rpc.ErrorInfo',reason:'SERVICE_DISABLED',domain:'googleapis.com',metadata:{service,consumer:'projects/123456789012',activationUrl:'https://evil.test/?token=TEST-SECRET'}}]}});
async function fixture(fn,override){
 const dir=await mkdtemp(join(tmpdir(),'essentiel-diagnostic-')),f=makeFixture();
 const s=new ConnectedService({filename:join(dir,'vault'),env:fixtureEnv,fetchImpl:override?((url,options)=>override(url,options,f)):f.fetch});
 try{await fn({s,f,dir});}finally{await rm(dir,{recursive:true,force:true});}
}
for(const [service,url] of Object.entries(URLS))test(`diagnostics: ${service} SERVICE_DISABLED is actionable without exposing upstream payload`,()=>{
 const e=providerError(url,403,disabled());assert.equal(e.code,'GOOGLE_API_DISABLED');assert.equal(e.providerStatus,403);assert.equal(e.diagnostic.category,'api_disabled');assert.equal(e.diagnostic.service,service);assert.equal(e.diagnostic.project,'123456789012');assert.ok(e.diagnostic.consoleUrl.startsWith('https://console.cloud.google.com/apis/library/'));assert.equal(new URL(e.diagnostic.consoleUrl).searchParams.get('project'),'123456789012');assert.doesNotMatch(JSON.stringify(e),/TEST-SECRET|evil\.test/);
});
test('diagnostics: legacy accessNotConfigured response is classified',()=>{const e=providerError(URLS.mail,403,{error:{errors:[{reason:'accessNotConfigured'}]}});assert.equal(e.diagnostic.category,'api_disabled');});
test('diagnostics: legacy disabled message fallback does not claim a project from prose',()=>{const e=providerError(URLS.tasks,403,{error:{message:'Tasks API has not been used in project 123456789012 before or it is disabled.'}});assert.equal(e.diagnostic.category,'api_disabled');assert.equal(e.diagnostic.project,'');});
test('diagnostics: insufficient scope is different from API disabled',()=>{const e=providerError(URLS.mail,403,{error:{status:'PERMISSION_DENIED',details:[{'@type':'type.googleapis.com/google.rpc.ErrorInfo',reason:'ACCESS_TOKEN_SCOPE_INSUFFICIENT'}]}});assert.equal(e.diagnostic.category,'insufficient_scopes');assert.equal(e.code,'PERMISSION_REQUIRED');});
test('diagnostics: Workspace policy is not misrepresented as an OAuth client type problem',()=>{assert.equal(providerError(URLS.mail,403,{error:{errors:[{reason:'domainPolicy'}]}}).diagnostic.category,'admin_policy');});
test('diagnostics: 403 quota and 429 preserve original HTTP status and delay',()=>{for(const status of [403,429]){const e=providerError(URLS.calendar,status,{error:{errors:[{reason:'userRateLimitExceeded'}]}},'90');assert.equal(e.diagnostic.category,'quota');assert.equal(e.providerStatus,status);assert.equal(e.diagnostic.retryAfterSeconds,90);assert.equal(e.diagnostic.retryable,true);}});
test('diagnostics: unknown 403 stays unknown, not a guessed disabled API',()=>{const e=providerError(URLS.mail,403,{error:{message:'unknown secret',errors:[{reason:'secret_access_token_123'}]}});assert.equal(e.diagnostic.category,'forbidden');assert.equal(e.diagnostic.reason,'UNSPECIFIED');assert.doesNotMatch(JSON.stringify(e),/secret/);});
test('diagnostics: invalid_grant asks for consent, not blanket permissions',()=>{const e=providerError('https://oauth2.googleapis.com/token',400,{error:'invalid_grant',error_description:'SECRET'});assert.equal(e.code,'REAUTHORIZE');assert.equal(e.diagnostic.consoleUrl,'');assert.doesNotMatch(JSON.stringify(e),/SECRET/);});
test('diagnostics: service links cannot come from an arbitrary provider URL',()=>{assert.equal(googleConsoleUrl('unknown','123456789012'),'');assert.equal(new URL(googleConsoleUrl('mail','evil&token=secret')).search,'');});
test('diagnostics: HTML provider errors keep HTTP status but never reflect HTML',()=>fixture(async({s})=>{await assert.rejects(s.oauth.http(URLS.mail),e=>e.providerStatus===403&&e.diagnostic.category==='forbidden'&&!e.message.includes('<'));},()=>new Response('<h1>secret</h1>',{status:403})));
test('diagnostics: sync preserves structured errors and marks failure rather than empty success',()=>fixture(async({s})=>{seed(s,['google']);const snap=await s.sync('google');assert.equal(snap.syncState,'failed');assert.equal(snap.errors.length,3);assert.ok(snap.errors.every(e=>e.diagnostic.category==='api_disabled'));assert.equal(snap.mailUpdatedAt,undefined);assert.equal(snap.lastSuccessfulSync,undefined);},()=>Response.json(disabled(),{status:403})));
test('diagnostics: fresh failures retain prior data and its prior successful timestamp',()=>fixture(async({s,f})=>{seed(s,['google']);await s.sync('google');const before=structuredClone(s.status().snapshots.google);f.failures.push({path:'/gmail/v1/users/me/messages',status:403});const after=await s.sync('google');assert.equal(after.syncState,'partial');assert.deepEqual(after.messages,before.messages);assert.equal(after.mailUpdatedAt,before.mailUpdatedAt);assert.equal(after.errors[0].diagnostic.category,'forbidden');}));
test('diagnostics: tests only selected read capabilities and stores no returned content',()=>fixture(async({s,f})=>{
 seed(s,['google']);s.vault.state().accounts.google.scopes=[SCOPES.google.mail];const r=await s.diagnostics('google');assert.equal(r.readOnly,true);assert.equal(r.writesTested,false);assert.deepEqual(r.checks.map(c=>c.status),['ok','not_granted','not_granted','not_granted']);assert.equal(f.calls.length,1);assert.equal(f.calls[0].method,'GET');assert.equal(new URL(f.calls[0].url).searchParams.get('fields'),'messages(id)');assert.doesNotMatch(JSON.stringify(r),/message-google|TEST-TOKEN|subject|sender@/);assert.equal(s.vault.state().snapshots.google,undefined);
}));
test('diagnostics: all four selected services are checked without a write',()=>fixture(async({s,f})=>{seed(s,['google']);const r=await s.diagnostics('google');assert.ok(r.checks.every(c=>c.status==='ok'));assert.equal(f.calls.length,4);assert.ok(f.calls.every(c=>c.method==='GET'));assert.equal(s.status().diagnostics.google.provider,'google');}));
test('diagnostics: failed access tests stay service-specific and do not throw away other results',()=>fixture(async({s,f})=>{seed(s,['google']);f.failures.push({path:'/gmail/',status:403});const r=await s.diagnostics('google');assert.equal(r.checks[0].status,'error');assert.equal(r.checks[1].status,'ok');assert.equal(r.checks[2].status,'ok');assert.equal(r.checks[3].status,'ok');}));
test('diagnostics: rejected write remains rejected, never retried, and has an actionable diagnostic',()=>fixture(async({s,f})=>{seed(s,['google']);const a=await s.preview({provider:'google',kind:'draft',payload:{to:'target@example.test',subject:'TEST',body:'Test only'}});f.failures.push({method:'POST',path:'/drafts',status:403});const r=await s.execute({id:a.id,approvalHash:a.approvalHash,approved:true});assert.equal(r.status,'rejected');assert.equal(r.diagnostic.category,'forbidden');assert.equal(f.calls.filter(c=>c.method==='POST').length,1);}));
test('diagnostics: lock hides report; disconnect removes only its local report',()=>fixture(async({s})=>{seed(s,['google']);await s.diagnostics('google');await s.vault.unlock('test passphrase at least twelve');await s.manageVault('lock');assert.deepEqual(s.status().diagnostics,{});await s.manageVault('unlock','test passphrase at least twelve');assert.ok(s.status().diagnostics.google);await s.disconnect('google');assert.equal(s.status().diagnostics.google,undefined);}));
test('unified HTTP: root and legacy workspace serve the exact same shell and both engines',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'essentiel-unified-'));const app=createApp({apiKey:'',connectorOptions:{filename:join(dir,'vault'),env:{}}});app.listen(0,'127.0.0.1');await once(app,'listening');const origin=`http://127.0.0.1:${app.address().port}`;
 try{const root=await(await fetch(origin+'/')).text();assert.equal(root,await(await fetch(origin+'/workspace')).text());assert.match(root,/\/app\.js/);assert.match(root,/\/connected\.js/);assert.match(root,/connected-scoped\.css/);assert.equal((await fetch(origin+'/connected-scoped.css')).status,200);assert.doesNotMatch(root,/<iframe/i);
 const denied=await fetch(origin+'/api/connected/diagnostics',{method:'POST',headers:{'Content-Type':'application/json','X-Essentiel-Request':'1',Origin:'https://evil.test'},body:'{"provider":"google"}'});assert.equal(denied.status,403);
 const disconnected=await fetch(origin+'/api/connected/diagnostics',{method:'POST',headers:{'Content-Type':'application/json','X-Essentiel-Request':'1',Origin:origin},body:'{"provider":"google"}'});assert.equal(disconnected.status,409);
 }finally{app.closeAllConnections();await new Promise(r=>app.close(r));await rm(dir,{recursive:true,force:true});}
});
